---

- name: Create SYS Folder
  f5bigip_sys_folder:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ folder_name }}"
    description: "{{ folder_description }}"
    sub_path: /
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create SYS Folder
  assert:
    that:
      - result|changed

# Not idempotent!!
#- name: Create SYS Folder (idempotent)
#  f5bigip_sys_folder:
#    f5bigip_hostname: "{{ inventory_hostname }}"
#    f5bigip_username: "{{ bigip01_username }}"
#    f5bigip_password: "{{ bigip01_password }}"
#    f5bigip_port: "{{ bigip01_port }}"
#    name: "{{ folder_name }}"
#    description: "{{ folder_description }}"
#    sub_path: "/"
#    state: present
#  delegate_to: localhost
#  register: result
#
#- name: Assert Create SYS Folder (idempotent)
#  assert:
#    that:
#      - not result|changed

- name: Delete SYS Folder
  f5bigip_sys_folder:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ folder_name }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Delete SYS Folder
  assert:
    that:
      - result|changed

- name: Delete SYS Folder (idempotent)
  f5bigip_sys_folder:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ folder_name }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Delete SYS Folder (idempotent)
  assert:
    that:
      - not result|changed