---

- name: Create SYS Folder
  f5bigip_sys_folder:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ folder_name }}"
    description: "{{ folder_description }}"
    sub_path: /
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create SYS Folder
  assert:
    that:
      - result|changed

- name: Create SYS Folder (idempotent)
  f5bigip_sys_folder:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ folder_name }}"
    description: "{{ folder_description }}"
    sub_path: /
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create SYS Folder (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete SYS Folder
  f5bigip_sys_folder:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ folder_name }}"
    sub_path: /
    state: absent
  delegate_to: localhost
  register: result

- name: Delete SYS Folder
  assert:
    that:
      - result|changed

- name: Delete SYS Folder (idempotent)
  f5bigip_sys_folder:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ folder_name }}"
    sub_path: /
    state: absent
  delegate_to: localhost
  register: result

- name: Delete SYS Folder (idempotent)
  assert:
    that:
      - not result|changed