---

- name: Create LTM NAT
  f5bigip_ltm_nat:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ nat_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ nat_description }}"
    originating_address: "{{ nat_originating_address }}"
    translation_address: "{{ nat_translation_address }}"
    vlans_enabled: "{{ nat_vlans_enabled }}"
    vlans: "{{ nat_vlans }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM NAT
  assert:
    that:
      - result|changed

- name: Create LTM NAT (idempotent)
  f5bigip_ltm_nat:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ nat_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ nat_description }}"
    originating_address: "{{ nat_originating_address }}"
    translation_address: "{{ nat_translation_address }}"
    vlans_enabled: "{{ nat_vlans_enabled }}"
    vlans: "{{ nat_vlans }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM NAT (idempotent)
  assert:
    that:
      - not result|changed
    
- name: Change LTM NAT description and stp
  f5bigip_ltm_nat:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ nat_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ nat_description }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM NAT description
  assert:
    that:
      - result|changed

- name: Change LTM NAT description (idempotent)
  f5bigip_ltm_nat:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ nat_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ nat_description }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM NAT description (idempotent)
  assert:
    that:
      - not result|changed 

- name: Delete LTM NAT
  f5bigip_ltm_nat:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ nat_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM NAT
  assert:
    that:
      - result|changed

- name: Delete LTM NAT (idempotent)
  f5bigip_ltm_nat:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ nat_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM NAT (idempotent)
  assert:
    that:
      - not result|changed