---

- name: Create NET Route-Domain
  f5bigip_net_route_domain:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ rd_name }}"
    id: "{{ rd_id }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create NET Route-Domain
  assert:
    that:
      - result|changed

- name: Create NET Route-Domain (idempotent)
  f5bigip_net_route_domain:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ rd_name }}"
    id: "{{ rd_id }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create NET Route-Domain (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete NET Route-Domain
  f5bigip_net_route_domain:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ rd_name }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete NET Route-Domain
  assert:
    that:
      - result|changed

- name: Delete NET Route-Domain (idempotent)
  f5bigip_net_route_domain:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ rd_name }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete NET Route-Domain (idempotent)
  assert:
    that:
      - not result|changed