---

- name: Upload a Data Group List
  f5bigip_shared_file_transfer_upload:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    filepathname: "{{ dg_filepathname }}"
    state: present
  delegate_to: localhost
  register: result

- name: Upload a Data Group List
  assert:
    that:
      - result|changed

- name: Upload a Key
  f5bigip_shared_file_transfer_upload:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    filepathname: "{{ key_filepathname }}"
    state: present
  delegate_to: localhost
  register: result

- name: Upload a Key
  assert:
    that:
      - result|changed

- name: Upload a Cert
  f5bigip_shared_file_transfer_upload:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    filepathname: "{{ cert_filepathname }}"
    state: present
  delegate_to: localhost
  register: result

- name: Upload a Cert
  assert:
    that:
      - result|changed