---

- name: Add SYS DNS Name Servers
  f5bigip_sys_dns:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name_servers: "{{ name_servers }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Add SYS DNS Name Servers
  assert:
    that:
      - result|changed

- name: Add SYS DNS Name Servers (idempotent)
  f5bigip_sys_dns:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name_servers: "{{ name_servers }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Add SYS DNS Name Servers (idempotent)
  assert:
    that:
      - not result|changed

- name: Remove SYS DNS Name Servers
  f5bigip_sys_dns:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name_servers: "{{ name_servers }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Remove SYS DNS Name Servers
  assert:
    that:
      - result|changed

- name: Remove SYS DNS Name Servers (idempotent)
  f5bigip_sys_dns:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name_servers: "{{ name_servers }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Remove SYS DNS Name Servers (idempotent)
  assert:
    that:
      - not result|changed