---

- name: Upload LTM External Data-Group List
  f5bigip_shared_file_transfer_upload:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    filepathname: "{{ ext_dg_filepathname }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Upload External Data-Group List
  assert:
    that:
      - result|changed

- name: Create SYS Data-Group file
  f5bigip_sys_file_data_group:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ ext_dg_filename }}"
    partition: Common
    source_path: "{{ ext_dg_source_path }}"
    type: string
    state: present
  delegate_to: localhost

- name: Assert Create SYS Data-Group file
  assert:
    that:
      - result|changed

# Not idempotent!!
#- name: Create SYS Data-Group file (idempotent)
#  f5bigip_sys_file_data_group:
#    f5_hostname: "{{ bigip_host }}"
#    f5_username: "{{ bigip_username }}"
#    f5_password: "{{ bigip_password }}"
#    f5_port: "{{ bigip_port }}"
#    name: "{{ ext_dg_filename }}"
#    partition: Common
#    source_path: "{{ ext_dg_source_path }}"
#    type: string
#    state: present
#  delegate_to: localhost
#
#- name: Assert Create SYS Data-Group file (idempotent)
#  assert:
#    that:
#      - not result|changed

- name: Delete SYS Data-Group file
  f5bigip_sys_file_data_group:
    f5_hostname: "{{ bigip_host }}"
    f5_username: "{{ bigip_username }}"
    f5_password: "{{ bigip_password }}"
    f5_port: "{{ bigip_port }}"
    name: "{{ ext_dg_filename }}"
    partition: Common
    state: absent
  delegate_to: localhost

- name: Assert Delete SYS Data-Group file
  assert:
    that:
      - result|changed

# Not idempotent!!
#- name: Delete SYS Data-Group file (idempotent)
#  f5bigip_sys_file_data_group:
#    f5_hostname: "{{ bigip_host }}"
#    f5_username: "{{ bigip_username }}"
#    f5_password: "{{ bigip_password }}"
#    f5_port: "{{ bigip_port }}"
#    name: "{{ ext_dg_filename }}"
#    partition: Common
#    state: absent
#  delegate_to: localhost
#
#- name: Assert Delete SYS Data-Group file (idempotent)
#  assert:
#    that:
#      - not result|changed