---

- name: Disable SYS DB Setup Utility Wizard
  f5bigip_sys_db:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ db_variable_name }}"
    value: "{{ db_variable_value }}"
  delegate_to: localhost
  register: result

- name: Assert Disable SYS DB Setup Utility Wizard
  assert:
    that:
      - result|changed
  ignore_errors: yes

- name: Disable SYS DB Setup Utility Wizard (idempotent)
  f5bigip_sys_db:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ bigip01_username }}"
    f5bigip_password: "{{ bigip01_password }}"
    f5bigip_port: "{{ bigip01_port }}"
    name: "{{ db_variable_name }}"
    value: "{{ db_variable_value }}"
  delegate_to: localhost
  register: result

- name: Assert Disable SYS DB Setup Utility Wizard (idempotent)
  assert:
    that:
      - not result|changed

#- name: Reset SYS DB Setup Wizard to Default
#  f5bigip_sys_db:
#    f5bigip_hostname: "{{ inventory_hostname }}"
#    f5bigip_username: "{{ bigip01_username }}"
#    f5bigip_password: "{{ bigip01_password }}"
#    f5bigip_port: "{{ bigip01_port }}"
#    name: "{{ db_variable_name }}"
#    reset_to_default: True
#  delegate_to: localhost
#  register: result
#
#- name: Assert Disable SYS DB Setup Wizard
#  assert:
#    that:
#      - result|changed