---

- name: Change SYS Provision level
  f5bigip_sys_provision:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ provision_name }}"
    level: "{{ provision_level }}"
  delegate_to: localhost
  register: result

- name: Assert Change SYS Provision level
  assert:
    that:
      - result|changed
  
- name: Change SYS Provision level (idempotent)
  f5bigip_sys_provision:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ provision_name }}"
    level: "{{ provision_level }}"
  delegate_to: localhost
  register: result

- name: Assert Change SYS Provision level (idempotent)
  assert:
    that:
      - not result|changed

- name: Change SYS Provision level to default
  f5bigip_sys_provision:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ provision_name }}"
    level: "{{ provision_level_default }}"
  delegate_to: localhost
  register: result

- name: Assert Change SYS Provision level to default
  assert:
    that:
      - result|changed

- name: Change SYS Provision level to default (idempotent)
  f5bigip_sys_provision:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ provision_name }}"
    level: "{{ provision_level_default }}"
  delegate_to: localhost
  register: result

- name: Assert Change SYS Provision level to default (idempotent)
  assert:
    that:
      - not result|changed