---

- name: Add SYS SSHD allow clients
  f5bigip_sys_sshd:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    allow: "{{ sshd_allow_clients }}"
    state: "present"
  delegate_to: localhost
  register: result

- name: Assert Add SYS SSHD allow clients
  assert:
    that:
      - result|changed

- name: Add SYS SSHD allow clients (idempotent check)
  f5bigip_sys_sshd:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    allow: "{{ sshd_allow_clients }}"
    state: "present"
  delegate_to: localhost
  register: result

- name: Assert Add SYS SSHD allow clients (idempotent check)
  assert:
    that:
      - not result|changed

- name: Add SYS SSHD banner
  f5bigip_sys_sshd:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    banner: "{{ sshd_banner }}"
    banner_text: "{{ sshd_banner_text }}"
  delegate_to: localhost
  register: result

- name: Assert Add SYS SSHD banner
  assert:
    that:
      - result|changed

- name: Change SYS SSHD inactivity timeout
  f5bigip_sys_sshd:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    inactivity_timeout: "{{ sshd_inactivity_timeout }}"
  delegate_to: localhost
  register: result

- name: Assert Change SYS SSHD inactivity timeout
  assert:
    that:
      - result|changed

- name: Remove SYS SSHD allow clients
  f5bigip_sys_sshd:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    allow: "{{ sshd_allow_clients }}"
    state: "absent"
  delegate_to: localhost
  register: result

- name: Assert Remove SYS SSHD allow clients
  assert:
    that:
      - result|changed

- name: Disable SYS SSHD banner
  f5bigip_sys_sshd:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    banner: "disabled"
    banner_text: ""
  delegate_to: localhost
  register: result

- name: Assert Disable SYS SSHD banner
  assert:
    that:
      - result|changed

- name: Disable SYS SSHD inactivity timeout
  f5bigip_sys_sshd:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    inactivity_timeout: 0
  delegate_to: localhost
  register: result

- name: Assert Disable SYS SSHD inactivity timeout
  assert:
    that:
      - result|changed