---

- name: Add SYS NTP Servers
  f5bigip_sys_ntp:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    servers: "{{ ntp_servers_add }}"
    timezone: "{{ ntp_timezone }}"
    state: "present"
  delegate_to: localhost
  register: result

- name: Assert Add SYS NTP Servers
  assert:
    that:
      - result|changed

- name: Add SYS NTP Servers (idempotent check)
  f5bigip_sys_ntp:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    servers: "{{ ntp_servers_add }}"
    timezone: "{{ ntp_timezone }}"
    state: "present"
  delegate_to: localhost
  register: result

- name: Assert Add SYS NTP Servers (idempotent check)
  assert:
    that:
      - not result|changed

- name: Remove SYS NTP Servers
  f5bigip_sys_ntp:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    servers: "{{ ntp_servers_remove }}"
    state: "absent"
  delegate_to: localhost
  register: result

- name: Assert Remove SYS NTP Servers
  assert:
    that:
      - result|changed