---

- name: Gather BIG-IP facts
  f5bigip_facts:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    object: "{{ item }}"
  with_items: "{{ facts_objects }}"
  delegate_to: localhost
  register: result
  

- name: Filter BIG-IP facts
  f5bigip_facts:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    object: "{{ item }}"
    filter: "{{ facts_filter }}"
    select: "{{ facts_select }}"
  with_items: "{{ facts_objects }}"
  delegate_to: localhost
  register: result