---

- name: Change GTM Global Load-Balancing Settings ignore path ttl
  f5bigip_gtm_global_settings_load_balancing:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    ignore_path_ttl: "{{ global_settings_load_balancing_ignore_path_ttl }}"
  delegate_to: localhost
  register: result

- name: Assert Change GTM Global Load-Balancing Settings ignore path ttl
  assert:
    that:
      - result|changed

- name: Change GTM Global Load-Balancing Settings ignore path ttl (idempotent)
  f5bigip_gtm_global_settings_load_balancing:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    ignore_path_ttl: "{{ global_settings_load_balancing_ignore_path_ttl }}"
  delegate_to: localhost
  register: result

- name: Assert Change GTM Global Load-Balancing Settings ignore path ttl (idempotent)
  assert:
    that:
      - not result|changed

- name: Change GTM Global Load-Balancing Settings ignore path ttl to default
  f5bigip_gtm_global_settings_load_balancing:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    ignore_path_ttl: "{{ global_settings_load_balancing_ignore_path_ttl_default }}"
  delegate_to: localhost
  register: result

- name: Assert Change GTM Global Load-Balancing Settings ignore path ttl to default
  assert:
    that:
      - result|changed

- name: Change GTM Global Load-Balancing Settings ignore path ttl to default (idempotent)
  f5bigip_gtm_global_settings_load_balancing:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    ignore_path_ttl: "{{ global_settings_load_balancing_ignore_path_ttl_default }}"
  delegate_to: localhost
  register: result

- name: Assert Change GTM Global Load-Balancing Settings ignore path ttl to default (idempotent)
  assert:
    that:
      - not result|changed