---

- name: Create LTM Cookie Persistence profile
  f5bigip_ltm_persistence_cookie:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ persist_cookie_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ persist_cookie_description }}"
    defaults_from: "{{ persist_cookie_defaults_from }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Cookie Persistence profile
  assert:
    that:
      - result|changed

- name: Create LTM Cookie Persistence profile (idempotent)
  f5bigip_ltm_persistence_cookie:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ persist_cookie_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ persist_cookie_description }}"
    defaults_from: "{{ persist_cookie_defaults_from }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Cookie Persistence profile (idempotent)
  assert:
    that:
      - not result|changed

- name: Change LTM Cookie Persistence description
  f5bigip_ltm_persistence_cookie:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ persist_cookie_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ persist_cookie_description }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM TCP Monitor description, interval and timeout
  assert:
    that:
      - result|changed

- name: Change LTM Cookie Persistence description (idempotent)
  f5bigip_ltm_persistence_cookie:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ persist_cookie_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ persist_cookie_description }}"
  delegate_to: localhost
  register: result

- name: Assert Change LTM Cookie Persistence description (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM Cookie Persistence profile
  f5bigip_ltm_persistence_cookie:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ persist_cookie_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Cookie Persistence profile
  assert:
    that:
      - result|changed

- name: Delete LTM Cookie Persistence profile (idempotent)
  f5bigip_ltm_persistence_cookie:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ persist_cookie_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Cookie Persistence profile (idempotent)
  assert:
    that:
      - not result|changed