---

common_name: example.localhost

files_path: "{{ role_path }}/files/"
rest_download_path: "/var/config/rest/downloads/"

key_name: "{{ common_name }}.key"
key_filepathname: "{{ files_path }}{{ key_name }}"
key_path: "{{ rest_download_path }}{{ key_name }}"

cert_name: "{{ common_name }}.crt"
cert_filepathname: "{{ files_path }}{{ cert_name }}"
cert_path: "{{ rest_download_path }}{{ cert_name }}"

profile_name: my_client_ssl_profile
profile_description: My client ssl profile