---

- name: Create GTM Datacenter
  f5bigip_gtm_datacenter:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ datacenter_name }}"
    partition: "{{ bigip_partition }}"
    contact: "{{ datacenter_contact }}"
    description: "{{ datacenter_description }}"
    location: "{{ datacenter_location }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create GTM Datacenter
  assert:
    that:
      - result|changed

- name: Create GTM Datacenter (idempotent)
  f5bigip_gtm_datacenter:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ datacenter_name }}"
    partition: "{{ bigip_partition }}"
    contact: "{{ datacenter_contact }}"
    description: "{{ datacenter_description }}"
    location: "{{ datacenter_location }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create GTM Datacenter (idempotent)
  assert:
    that:
      - not result|changed

- name: Modify GTM Datacenter description
  f5bigip_gtm_datacenter:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ datacenter_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ datacenter_description }}"
  delegate_to: localhost
  register: result

- name: Assert Modify GTM Datacenter description
  assert:
      that:
        - result|changed

- name: Modify GTM Datacenter description (idempotent)
  f5bigip_gtm_datacenter:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ datacenter_name }}"
    partition: "{{ bigip_partition }}"
    description: "new {{ datacenter_description }}"
  delegate_to: localhost
  register: result

- name: Assert Modify GTM Datacenter description (idempotent)
  assert:
      that:
        - not result|changed

- name: Delete GTM Datacenter
  f5bigip_gtm_datacenter:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ datacenter_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete GTM Datacenter
  assert:
    that:
      - result|changed

- name: Delete GTM Datacenter (idempotent)
  f5bigip_gtm_datacenter:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ datacenter_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete GTM Datacenter (idempotent)
  assert:
    that:
      - not result|changed