---

- name: Create NET Route
  f5bigip_net_route:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    name: "{{ route_name }}"
    partition: "{{ f5bigip_partition }}"
    description: "{{ route_description }}"
    network: "{{ route_network }}"
    gw: "{{ route_gw }}"
    state: "present"
  delegate_to: localhost
  register: result

- name: Assert Create NET Route
  assert:
    that:
      - result|changed

- name: Create NET Route (idempotent check)
  f5bigip_net_route:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    name: "{{ route_name }}"
    partition: "{{ f5bigip_partition }}"
    description: "{{ route_description }}"
    network: "{{ route_network }}"
    gw: "{{ route_gw }}"
    state: "present"
  delegate_to: localhost
  register: result

- name: Assert Create NET Route (idempotent check)
  assert:
    that:
      - not result|changed

- name: Change NET Route description and gateway
  f5bigip_net_route:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    name: "{{ route_name }}"
    partition: "{{ f5bigip_partition }}"
    description: "new {{ route_description }}"
    gw: "{{ route_new_gw }}"
  register: result

- name: Change NET Route description and gateway
  assert:
      that:
        - result|changed

- name: Delete NET Route
  f5bigip_net_route:
    f5bigip_hostname: "{{ inventory_hostname }}"
    f5bigip_username: "{{ f5bigip_username }}"
    f5bigip_password: "{{ f5bigip_password }}"
    f5bigip_port: "{{ f5bigip_port }}"
    name: "{{ route_name }}"
    partition: "{{ f5bigip_partition }}"
    state: "absent"
  delegate_to: localhost
  register: result

- name: Assert Delete NET Route
  assert:
    that:
      - result|changed