---

- name: Create LTM Pool
  f5bigip_ltm_pool:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ pool_name }}"
    partition: "{{ bigip_partition }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Pool
  assert:
    that:
      - result|changed

- name: Create LTM Virtual Server
  f5bigip_ltm_virtual:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_name }}"
    partition: "{{ bigip_partition }}"
    description: "{{ virtual_description }}"
    destination: "{{ virtual_destination }}"
    ip_protocol: "{{ virtual_ip_protocol }}"
    vlans: "{{ virtual_vlans }}"
    vlans_enabled: "{{ virtual_vlans_enabled }}"
    state: present
  delegate_to: localhost
  register: result

- name: Assert Create LTM Virtual Server
  assert:
    that:
      - result|changed

# Not idempotent !!
#- name: Create LTM Virtual Server (idempotent)
#  f5bigip_ltm_virtual:
#    f5_hostname: "{{ inventory_hostname }}"
#    f5_username: "{{ bigip01_username }}"
#    f5_password: "{{ bigip01_password }}"
#    f5_port: "{{ bigip01_port }}"
#    name: "{{ virtual_name }}"
#    partition: "{{ bigip_partition }}"
#    description: "{{ virtual_description }}"
#    destination: "{{ virtual_destination }}"
#    ip_protocol: "{{ virtual_ip_protocol }}"
#    vlans: "{{ virtual_vlans }}"
#    vlans_enabled: "{{ virtual_vlans_enabled }}"
#    state: present
#  delegate_to: localhost
#  register: result
#
#- name: Assert Create LTM Virtual Server (idempotent)
#  assert:
#    that:
#      - not result|changed

- name: Add LTM Virtual Server Profiles
  f5bigip_ltm_virtual_profile:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ item.name }}"
    partition: "{{ bigip_partition }}"
    context: "{{ item.context }}"
    virtual: "{{ virtual_name }}"
    state: present
  with_items: "{{ virtual_profiles }}"
  delegate_to: localhost
  register: result

- name: Assert Add LTM Virtual Server Profiles
  assert:
    that:
      - result|changed

- name: Delete LTM Virtual Server
  f5bigip_ltm_virtual:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Virtual Server
  assert:
    that:
      - result|changed

- name: Delete LTM Virtual Server (idempotent)
  f5bigip_ltm_virtual:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ virtual_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Virtual Server (idempotent)
  assert:
    that:
      - not result|changed

- name: Delete LTM Pool
  f5bigip_ltm_pool:
    f5_hostname: "{{ inventory_hostname }}"
    f5_username: "{{ bigip01_username }}"
    f5_password: "{{ bigip01_password }}"
    f5_port: "{{ bigip01_port }}"
    name: "{{ pool_name }}"
    partition: "{{ bigip_partition }}"
    state: absent
  delegate_to: localhost
  register: result

- name: Assert Delete LTM Pool
  assert:
    that:
      - result|changed